"""empty message

Revision ID: 02a2fe2ce989
Revises: 8ab0715a27e6
Create Date: 2019-08-30 18:47:57.772610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a2fe2ce989'
down_revision = '8ab0715a27e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('business_contact_no', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('business_email', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('contact_no', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('gst_no', sa.String(), nullable=True))
    op.add_column('booking', sa.Column('office_address', sa.String(), nullable=True))
    # op.drop_constraint('cart_deal_hotel_id_fkey', 'cart_deal', type_='foreignkey')
    # op.drop_column('cart_deal', 'hotel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('cart_deal', sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key('cart_deal_hotel_id_fkey', 'cart_deal', 'hotel', ['hotel_id'], ['id'])
    op.drop_column('booking', 'office_address')
    op.drop_column('booking', 'gst_no')
    op.drop_column('booking', 'contact_no')
    op.drop_column('booking', 'company_name')
    op.drop_column('booking', 'business_email')
    op.drop_column('booking', 'business_contact_no')
    # ### end Alembic commands ###
