"""empty message

Revision ID: 03b2bc2ce35a
Revises: fcda23b4a3ae
Create Date: 2019-08-28 16:33:45.682579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b2bc2ce35a'
down_revision = 'fcda23b4a3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('b2b_lowest_price', sa.Boolean(), nullable=True))
    op.add_column('deal', sa.Column('b2c_lowest_price', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'b2c_lowest_price')
    op.drop_column('deal', 'b2b_lowest_price')
    # ### end Alembic commands ###
