"""empty message

Revision ID: 078d7d0e78fc
Revises: 88d872c500f1
Create Date: 2019-08-24 14:56:41.168473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '078d7d0e78fc'
down_revision = '88d872c500f1'
branch_labels = None
depends_on = None


def upgrade():
    bedtype = postgresql.ENUM('Single', 'Double', 'Queen', 'King', name='bedtype')
    bedtype.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility', sa.Column('bed_type', sa.Enum('Single', 'Double', 'Queen', 'King', name='bedtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'bed_type')
    bedtype = postgresql.ENUM('Single', 'Double', 'Queen', 'King', name='bedtype')
    bedtype.drop(op.get_bind())
    # ### end Alembic commands ###
