"""empty message

Revision ID: 29e859daf979
Revises: ddf2681ba13c
Create Date: 2019-07-16 00:06:10.702474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e859daf979'
down_revision = 'ddf2681ba13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotel_phone_key', 'hotel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hotel_phone_key', 'hotel', ['phone'])
    # ### end Alembic commands ###
