"""empty message

Revision ID: 354ec7ee8505
Revises: b13bcfe7e5fb
Create Date: 2019-10-07 17:33:31.554836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354ec7ee8505'
down_revision = 'b13bcfe7e5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('total_rooms', sa.Integer(), nullable=True))
    op.add_column('hotel', sa.Column('total_rooms_booked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'total_rooms_booked')
    op.drop_column('hotel', 'total_rooms')
    # ### end Alembic commands ###
