"""empty message

Revision ID: 3b55a350f0ec
Revises: 70329be90606
Create Date: 2019-08-03 13:09:09.896165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b55a350f0ec'
down_revision = '70329be90606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('booking', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'booking_date')
    # ### end Alembic commands ###
