"""empty message

Revision ID: 42bd700fa350
Revises: aa74976ebd20
Create Date: 2019-08-22 20:25:12.650374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42bd700fa350'
down_revision = 'aa74976ebd20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_type')
    # ### end Alembic commands ###
