"""empty message

Revision ID: 4dfec47430f1
Revises: 8321461dbe43
Create Date: 2019-07-31 11:03:41.865432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfec47430f1'
down_revision = '8321461dbe43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('age_of_child_1', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column('age_of_child_2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'age_of_child_2')
    op.drop_column('member', 'age_of_child_1')
    # ### end Alembic commands ###
