"""empty message

Revision ID: 5445e3355101
Revises: 72406f285dfc
Create Date: 2019-06-25 15:37:43.236548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5445e3355101'
down_revision = '72406f285dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('business_deal', sa.Boolean(), nullable=False))
    op.alter_column('deal', 'weekend',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'weekend',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('deal', 'business_deal')
    # ### end Alembic commands ###
