"""empty message

Revision ID: 582caa803788
Revises: 58e0e50cb407
Create Date: 2019-08-21 21:12:56.656519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '582caa803788'
down_revision = '58e0e50cb407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('total_no_of_deals', sa.Integer(), nullable=False),
    sa.Column('total_booking_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.create_table('cart_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('current_deal_amount', sa.Integer(), nullable=True),
    sa.Column('ci_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('co_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_deals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_deal_id'), 'cart_deal', ['id'], unique=False)
    op.drop_index('ix_member_id', table_name='member')
    op.drop_table('member')
    op.add_column('booking_deal', sa.Column('current_deal_amount', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('sold_out', sa.Boolean(), nullable=True))
    op.drop_column('deal', 'weekend')
    op.add_column('price_calendar', sa.Column('sold_out', sa.Boolean(), nullable=True))
    op.add_column('price_calendar', sa.Column('weekend', sa.Boolean(), nullable=True))
    op.add_column('room', sa.Column('max_no_of_guest', sa.Integer(), nullable=True))
    op.drop_column('room', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('room', 'max_no_of_guest')
    op.drop_column('price_calendar', 'weekend')
    op.drop_column('price_calendar', 'sold_out')
    op.add_column('deal', sa.Column('weekend', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'sold_out')
    op.drop_column('booking_deal', 'current_deal_amount')
    op.create_table('member',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('no_of_adults', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('children', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('age_of_child_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age_of_child_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='member_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='member_pkey'),
    sa.UniqueConstraint('room_id', name='member_room_id_key')
    )
    op.create_index('ix_member_id', 'member', ['id'], unique=False)
    op.drop_index(op.f('ix_cart_deal_id'), table_name='cart_deal')
    op.drop_table('cart_deal')
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
