"""empty message

Revision ID: 58e0e50cb407
Revises: c075c3bcce3b
Create Date: 2019-08-21 00:59:24.821062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e0e50cb407'
down_revision = 'c075c3bcce3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'price')
    # ### end Alembic commands ###
