"""empty message

Revision ID: 594361616f63
Revises: e9382915bf50
Create Date: 2019-08-17 13:50:07.337973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594361616f63'
down_revision = 'e9382915bf50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('selling_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'selling_price')
    # ### end Alembic commands ###
