"""empty message

Revision ID: 5f97ee154fd6
Revises: 90f97d762a96
Create Date: 2019-10-20 13:07:58.796352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5f97ee154fd6'
down_revision = '90f97d762a96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status = postgresql.ENUM('P', 'F', 'S', name='status')
    status.create(op.get_bind())
    op.add_column('package_booking', sa.Column('status', sa.Enum('p', 'F', 'S', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_booking', 'status')
    status = postgresql.ENUM('P', 'F', 'S', name='status')
    status.drop(op.get_bind())
    # ### end Alembic commands ###
