"""empty message

Revision ID: 70329be90606
Revises: 835325269367
Create Date: 2019-08-01 14:22:52.541475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70329be90606'
down_revision = '835325269367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_deal_id'), 'booking_deal', ['id'], unique=False)
    op.add_column('booking', sa.Column('partner_id', sa.Integer(), nullable=False))
    op.drop_constraint('booking_deal_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'vendor_id')
    op.drop_column('booking', 'deal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('booking_deal_id_fkey', 'booking', 'deal', ['deal_id'], ['id'])
    op.drop_column('booking', 'partner_id')
    op.drop_index(op.f('ix_booking_deal_id'), table_name='booking_deal')
    op.drop_table('booking_deal')
    # ### end Alembic commands ###
