"""empty message

Revision ID: 7205c244bbda
Revises: 
Create Date: 2019-01-27 18:55:16.442738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7205c244bbda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_collection_id'), 'hotel_collection', ['id'], unique=False)
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_id'), 'website', ['id'], unique=False)
    op.create_table('collection_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_collection_id', sa.Integer(), nullable=False),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('featured_product', sa.Boolean(), nullable=True),
    sa.Column('product_desc', sa.Text(), nullable=True),
    sa.Column('product_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_collection_id'], ['hotel_collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_product_id'), 'collection_product', ['id'], unique=False)
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('is_partner', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['hotel_collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_hotel_id'), 'hotel', ['id'], unique=False)
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('conference_room', sa.Boolean(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('couple_friendly', sa.Boolean(), nullable=True),
    sa.Column('express_check_in_out', sa.Boolean(), nullable=True),
    sa.Column('laundry_service', sa.Boolean(), nullable=True),
    sa.Column('indoor_swimming_pool', sa.Boolean(), nullable=True),
    sa.Column('outdoor_swimming_pool', sa.Boolean(), nullable=True),
    sa.Column('porter_service', sa.Boolean(), nullable=True),
    sa.Column('Room_cleaning_service', sa.Boolean(), nullable=True),
    sa.Column('terrace', sa.Boolean(), nullable=True),
    sa.Column('child_baby_cot', sa.Boolean(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('doorman', sa.Boolean(), nullable=True),
    sa.Column('hairdresser', sa.Boolean(), nullable=True),
    sa.Column('banquets', sa.Boolean(), nullable=True),
    sa.Column('non_smoking_smoking_rooms', sa.Boolean(), nullable=True),
    sa.Column('pet_allowance', sa.Boolean(), nullable=True),
    sa.Column('lift', sa.Boolean(), nullable=True),
    sa.Column('bar', sa.Boolean(), nullable=True),
    sa.Column('gym', sa.Boolean(), nullable=True),
    sa.Column('pool', sa.Boolean(), nullable=True),
    sa.Column('restaurant', sa.Boolean(), nullable=True),
    sa.Column('spa', sa.Boolean(), nullable=True),
    sa.Column('wifi_in_lobby', sa.Boolean(), nullable=True),
    sa.Column('twenty_four_hr_reception', sa.Boolean(), nullable=True),
    sa.Column('twenty_four_hr_room_service', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id')
    )
    op.create_index(op.f('ix_amenity_id'), 'amenity', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('room_type', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('other_room_type', sa.String(), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breakfast', sa.Boolean(), nullable=True),
    sa.Column('balcony', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('hotel_url', sa.String(), nullable=True),
    sa.Column('weekend', sa.Boolean(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_id'), 'deal', ['id'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bed_type', sa.Integer(), nullable=True),
    sa.Column('no_of_bed', sa.Integer(), nullable=True),
    sa.Column('bathroom_with_shower', sa.Boolean(), nullable=True),
    sa.Column('bathroom_nightie', sa.Boolean(), nullable=True),
    sa.Column('wardrobes_closet', sa.Boolean(), nullable=True),
    sa.Column('room_slipper', sa.Boolean(), nullable=True),
    sa.Column('morning_newspaper', sa.Boolean(), nullable=True),
    sa.Column('food_serve_at_room', sa.Boolean(), nullable=True),
    sa.Column('ironing_facility', sa.Boolean(), nullable=True),
    sa.Column('view', sa.Boolean(), nullable=True),
    sa.Column('free_toiletries', sa.Boolean(), nullable=True),
    sa.Column('bathroom_towels', sa.Boolean(), nullable=True),
    sa.Column('bathroom_cosmetics', sa.Boolean(), nullable=True),
    sa.Column('weighing_machine', sa.Boolean(), nullable=True),
    sa.Column('room_seating_area', sa.Boolean(), nullable=True),
    sa.Column('free_evening_snacks', sa.Boolean(), nullable=True),
    sa.Column('ac', sa.Boolean(), nullable=True),
    sa.Column('hairdryer', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('tv', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.Boolean(), nullable=True),
    sa.Column('room_safe', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('desk', sa.Boolean(), nullable=True),
    sa.Column('fan', sa.Boolean(), nullable=True),
    sa.Column('electric_kettle', sa.Boolean(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_facility_id'), 'facility', ['id'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_of_adults', sa.Integer(), nullable=True),
    sa.Column('children', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_facility_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_deal_id'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_amenity_id'), table_name='amenity')
    op.drop_table('amenity')
    op.drop_index(op.f('ix_hotel_id'), table_name='hotel')
    op.drop_table('hotel')
    op.drop_index(op.f('ix_collection_product_id'), table_name='collection_product')
    op.drop_table('collection_product')
    op.drop_index(op.f('ix_website_id'), table_name='website')
    op.drop_table('website')
    op.drop_index(op.f('ix_hotel_collection_id'), table_name='hotel_collection')
    op.drop_table('hotel_collection')
    # ### end Alembic commands ###
True