"""empty message

Revision ID: 72406f285dfc
Revises: 7205c244bbda
Create Date: 2019-06-22 14:51:53.813513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72406f285dfc'
down_revision = '7205c244bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotel_collection_id_key', 'hotel', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('hotel_collection_id_key', 'hotel', ['collection_id'])
    # ### end Alembic commands ###
