"""empty message

Revision ID: 7ed5a32152d1
Revises: 03b2bc2ce35a
Create Date: 2019-08-29 12:05:55.794437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed5a32152d1'
down_revision = '03b2bc2ce35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('b2b_selected_deal', sa.Boolean(), nullable=True))
    op.add_column('deal', sa.Column('b2c_selected_deal', sa.Boolean(), nullable=True))
    op.drop_column('deal', 'selected_deal')
    op.add_column('facility', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.drop_column('room', 'balcony')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('balcony', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('facility', 'balcony')
    op.add_column('deal', sa.Column('selected_deal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'b2c_selected_deal')
    op.drop_column('deal', 'b2b_selected_deal')
    # ### end Alembic commands ###
