"""empty message

Revision ID: 802fc5996861
Revises: c771f4f2e2ee
Create Date: 2019-08-22 20:31:28.272270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802fc5996861'
down_revision = 'c771f4f2e2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility', sa.Column('jacuzzi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'jacuzzi')
    # ### end Alembic commands ###
