"""empty message

Revision ID: 835325269367
Revises: 4dfec47430f1
Create Date: 2019-07-31 17:51:32.216632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835325269367'
down_revision = '4dfec47430f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'date')
    # ### end Alembic commands ###
