"""empty message

Revision ID: 8ab0715a27e6
Revises: f624971d3885
Create Date: 2019-08-30 16:23:10.626012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab0715a27e6'
down_revision = 'f624971d3885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_deal', sa.Column('base_booking_price', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('final_price', sa.Integer(), nullable=True))
    op.drop_column('booking_deal', 'selling_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_deal', sa.Column('selling_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking_deal', 'final_price')
    op.drop_column('booking_deal', 'base_booking_price')
    # ### end Alembic commands ###
