"""empty message

Revision ID: 90f97d762a96
Revises: d86d83eb4168
Create Date: 2019-10-20 13:07:34.284804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f97d762a96'
down_revision = 'd86d83eb4168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('package_url', sa.String(), nullable=True),
    sa.Column('featured_image', sa.String(), nullable=True),
    sa.Column('accommodation_type', sa.Integer(), nullable=True),
    sa.Column('rating', sa.DECIMAL(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('price_for_adult', sa.Integer(), nullable=True),
    sa.Column('price_for_child', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_till', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_id'), 'package', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('experience_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_table('inclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('hotel', sa.Boolean(), nullable=True),
    sa.Column('visa', sa.Boolean(), nullable=True),
    sa.Column('transfer', sa.Boolean(), nullable=True),
    sa.Column('flight', sa.Boolean(), nullable=True),
    sa.Column('meals', sa.Boolean(), nullable=True),
    sa.Column('experiences', sa.Boolean(), nullable=True),
    sa.Column('hotel_assistance', sa.Boolean(), nullable=True),
    sa.Column('activities', sa.Boolean(), nullable=True),
    sa.Column('airport_transfer', sa.Boolean(), nullable=True),
    sa.Column('inter_city_transfer', sa.Boolean(), nullable=True),
    sa.Column('sightseeing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_index(op.f('ix_inclusions_id'), 'inclusions', ['id'], unique=False)
    op.create_table('package_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_booking_no', sa.String(), nullable=True),
    sa.Column('trip_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trip_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_mail', sa.String(), nullable=True),
    sa.Column('customer_contact', sa.String(), nullable=True),
    sa.Column('price_per_adult', sa.Integer(), nullable=True),
    sa.Column('price_per_child', sa.Integer(), nullable=True),
    sa.Column('no_of_adult', sa.Integer(), nullable=True),
    sa.Column('no_of_child', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_booking_id'), 'package_booking', ['id'], unique=False)
    op.alter_column('cart', 'total_no_of_deals',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'total_no_of_deals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_package_booking_id'), table_name='package_booking')
    op.drop_table('package_booking')
    op.drop_index(op.f('ix_inclusions_id'), table_name='inclusions')
    op.drop_table('inclusions')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_package_id'), table_name='package')
    op.drop_table('package')
    # ### end Alembic commands ###
