"""empty message

Revision ID: 9c639292276f
Revises: 02a2fe2ce989
Create Date: 2019-09-04 11:54:10.051411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c639292276f'
down_revision = '02a2fe2ce989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_calendar', sa.Column('b2b_final_price', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('b2c_final_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_calendar', 'b2c_final_price')
    op.drop_column('price_calendar', 'b2b_final_price')
    # ### end Alembic commands ###
