"""empty message

Revision ID: a82dba001689
Revises: 29e859daf979
Create Date: 2019-07-23 01:39:19.598645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82dba001689'
down_revision = '29e859daf979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('b2b_lowest_price_room', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'b2b_lowest_price_room')
    # ### end Alembic commands ###
