"""empty message

Revision ID: aa74976ebd20
Revises: 582caa803788
Create Date: 2019-08-22 20:24:22.984892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa74976ebd20'
down_revision = '582caa803788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_type', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
