"""empty message

Revision ID: ad5462444fe6
Revises: f4350f8e3d3a
Create Date: 2019-06-25 18:04:12.595191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad5462444fe6'
down_revision = 'f4350f8e3d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('country', sa.String(), nullable=True))
    op.drop_column('room', 'check_in')
    op.drop_column('room', 'check_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('check_out', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('check_in', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('hotel', 'country')
    # ### end Alembic commands ###
