"""empty message

Revision ID: c075c3bcce3b
Revises: cfe35a7c1c18
Create Date: 2019-08-19 12:00:13.306901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c075c3bcce3b'
down_revision = 'cfe35a7c1c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'website_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hotel', 'is_partner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('is_partner', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('deal', 'website_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
