"""empty message

Revision ID: ca69b3770fca
Revises: 3b55a350f0ec
Create Date: 2019-08-08 14:17:27.585751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ca69b3770fca'
down_revision = '3b55a350f0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    mealplan = postgresql.ENUM('CP', 'MAP', 'EP', 'AP', name='mealplan')
    mealplan.create(op.get_bind())
    op.add_column('deal', sa.Column('base_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('commission_in_percentage', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('margin_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('meal_plan', sa.Enum('CP', 'MAP', 'EP', 'AP', name='mealplan'), nullable=True))
    op.add_column('deal', sa.Column('total_price', sa.Integer(), nullable=True))
    op.drop_column('deal', 'price')
    op.add_column('price_calendar', sa.Column('base_price', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('commission_in_percentage', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('margin_price', sa.Integer(), nullable=True))
    op.drop_column('price_calendar', 'available')
    op.drop_column('price_calendar', 'price')
    op.drop_column('room', 'breakfast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('breakfast', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('price_calendar', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('price_calendar', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('price_calendar', 'margin_price')
    op.drop_column('price_calendar', 'commission_in_percentage')
    op.drop_column('price_calendar', 'base_price')
    op.add_column('deal', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'total_price')
    op.drop_column('deal', 'meal_plan')
    mealplan = postgresql.ENUM('CP', 'MAP', 'EP', 'AP', name='mealplan')
    mealplan.drop(op.get_bind())
    op.drop_column('deal', 'margin_price')
    op.drop_column('deal', 'commission_in_percentage')
    op.drop_column('deal', 'base_price')
    # ### end Alembic commands ###
