"""empty message

Revision ID: cfe35a7c1c18
Revises: 594361616f63
Create Date: 2019-08-18 06:15:58.411849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe35a7c1c18'
down_revision = '594361616f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('total_booking_amount', sa.Integer(), nullable=True))
    op.drop_column('booking', 'guest_name')
    op.drop_column('booking', 'email')
    op.drop_column('booking', 'contact_no')
    op.add_column('booking_deal', sa.Column('base_price', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('ci_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking_deal', sa.Column('co_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking_deal', sa.Column('commission_in_percentage', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('contact_no', sa.String(), nullable=True))
    op.add_column('booking_deal', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('booking_deal', sa.Column('guest_fist_name', sa.String(), nullable=True))
    op.add_column('booking_deal', sa.Column('guest_last_name', sa.String(), nullable=True))
    op.add_column('booking_deal', sa.Column('margin_price', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('selling_price', sa.Integer(), nullable=True))
    op.add_column('booking_deal', sa.Column('ts_exclusive', sa.Boolean(), nullable=True))
    op.add_column('booking_deal', sa.Column('website_id', sa.Integer(), nullable=True))
    op.drop_constraint('booking_deal_deal_id_fkey', 'booking_deal', type_='foreignkey')
    op.create_foreign_key(None, 'booking_deal', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'booking_deal', 'website', ['website_id'], ['id'])
    op.drop_column('booking_deal', 'deal_id')
    op.add_column('deal', sa.Column('b2b_margin_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('b2b_selling_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('b2c_margin_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('b2c_selling_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('ts_exclusive', sa.Boolean(), nullable=True))
    op.drop_column('deal', 'selling_price')
    op.drop_column('deal', 'meal_plan')
    op.drop_column('deal', 'margin_price')
    op.drop_column('deal', 'business_deal')
    op.drop_column('deal', 'price')
    op.add_column('price_calendar', sa.Column('b2b_margin_price', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('b2b_selling_price', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('b2c_margin_price', sa.Integer(), nullable=True))
    op.add_column('price_calendar', sa.Column('b2c_selling_price', sa.Integer(), nullable=True))
    op.drop_column('price_calendar', 'margin_price')
    op.drop_column('price_calendar', 'selling_price')
    op.add_column('room', sa.Column('meal_plan', sa.Enum('CP', 'MAP', 'EP', 'AP', name='mealplan'), nullable=True))
    op.drop_column('room', 'other_room_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('other_room_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('room', 'meal_plan')
    op.add_column('price_calendar', sa.Column('selling_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('price_calendar', sa.Column('margin_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('price_calendar', 'b2c_selling_price')
    op.drop_column('price_calendar', 'b2c_margin_price')
    op.drop_column('price_calendar', 'b2b_selling_price')
    op.drop_column('price_calendar', 'b2b_margin_price')
    op.add_column('deal', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('business_deal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('margin_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('meal_plan', postgresql.ENUM('CP', 'MAP', 'EP', 'AP', name='mealplan'), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('selling_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'ts_exclusive')
    op.drop_column('deal', 'partner_id')
    op.drop_column('deal', 'b2c_selling_price')
    op.drop_column('deal', 'b2c_margin_price')
    op.drop_column('deal', 'b2b_selling_price')
    op.drop_column('deal', 'b2b_margin_price')
    op.add_column('booking_deal', sa.Column('deal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking_deal', type_='foreignkey')
    op.drop_constraint(None, 'booking_deal', type_='foreignkey')
    op.create_foreign_key('booking_deal_deal_id_fkey', 'booking_deal', 'deal', ['deal_id'], ['id'])
    op.drop_column('booking_deal', 'website_id')
    op.drop_column('booking_deal', 'ts_exclusive')
    op.drop_column('booking_deal', 'selling_price')
    op.drop_column('booking_deal', 'room_id')
    op.drop_column('booking_deal', 'partner_id')
    op.drop_column('booking_deal', 'margin_price')
    op.drop_column('booking_deal', 'guest_last_name')
    op.drop_column('booking_deal', 'guest_fist_name')
    op.drop_column('booking_deal', 'email')
    op.drop_column('booking_deal', 'contact_no')
    op.drop_column('booking_deal', 'commission_in_percentage')
    op.drop_column('booking_deal', 'co_date')
    op.drop_column('booking_deal', 'ci_date')
    op.drop_column('booking_deal', 'base_price')
    op.add_column('booking', sa.Column('contact_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('guest_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'total_booking_amount')
    # ### end Alembic commands ###
