"""empty message

Revision ID: d86d83eb4168
Revises: 354ec7ee8505
Create Date: 2019-10-07 18:31:08.173970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86d83eb4168'
down_revision = '354ec7ee8505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('primary_image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'primary_image')
    # ### end Alembic commands ###
