"""empty message

Revision ID: e9382915bf50
Revises: fe4c34444e92
Create Date: 2019-08-17 13:55:31.216357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9382915bf50'
down_revision = 'fe4c34444e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_calendar', sa.Column('selling_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_calendar', 'selling_price')
    # ### end Alembic commands ###
