"""empty message

Revision ID: f0e6294863ba
Revises: b3cc0ac1f3c2
Create Date: 2019-06-26 13:17:48.247195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e6294863ba'
down_revision = 'b3cc0ac1f3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('vendor_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'vendor_id')
    # ### end Alembic commands ###
