"""empty message

Revision ID: f4350f8e3d3a
Revises: 72406f285dfc
Create Date: 2019-06-25 15:42:33.060245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4350f8e3d3a'
down_revision = '72406f285dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('business_deal', sa.Boolean(), nullable=True))
    op.alter_column('deal', 'weekend',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'weekend',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('deal', 'business_deal')
    # ### end Alembic commands ###
