"""empty message

Revision ID: f624971d3885
Revises: 7ed5a32152d1
Create Date: 2019-08-29 14:07:25.171100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f624971d3885'
down_revision = '7ed5a32152d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('b2b_final_price', sa.Integer(), nullable=True))
    op.add_column('deal', sa.Column('b2c_final_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'b2c_final_price')
    op.drop_column('deal', 'b2b_final_price')
    # ### end Alembic commands ###
