"""empty message

Revision ID: fcda23b4a3ae
Revises: 078d7d0e78fc
Create Date: 2019-08-28 15:38:40.254998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcda23b4a3ae'
down_revision = '078d7d0e78fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('selected_deal', sa.Boolean(), nullable=True))
    op.drop_column('room', 'lowest_price_room')
    op.drop_column('room', 'b2b_lowest_price_room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('b2b_lowest_price_room', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('lowest_price_room', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'selected_deal')
    # ### end Alembic commands ###
