"""empty message

Revision ID: fe4c34444e92
Revises: ca69b3770fca
Create Date: 2019-08-08 16:11:54.993597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4c34444e92'
down_revision = 'ca69b3770fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('deal', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('deal', 'price')
    # ### end Alembic commands ###
