"""empty message

Revision ID: ff9b58f01a55
Revises: 9c639292276f
Create Date: 2019-09-04 19:03:02.256645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9b58f01a55'
down_revision = '9c639292276f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal', 'b2b_lowest_price')
    op.drop_column('deal', 'b2c_lowest_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('b2c_lowest_price', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('deal', sa.Column('b2b_lowest_price', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
